name: Bug Report
description: Report a bug in the VCP SDK
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please fill in the details below to help us diagnose the issue quickly.

  - type: dropdown
    id: sdk
    attributes:
      label: Affected SDK
      description: Which SDK are you using?
      options:
        - Python
        - Rust
        - TypeScript / WebMCP
        - Specification / Schemas
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: SDK version or commit hash
      placeholder: "e.g. 1.0.0, 0.1.0, or a2a515c"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear, concise description of the bug
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior
      placeholder: |
        1. Install the SDK with `pip install vcp-python`
        2. Run this code...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened (include error messages, tracebacks, or unexpected output)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Runtime details
      placeholder: |
        - OS: macOS 15.2 / Ubuntu 24.04 / Windows 11
        - Python: 3.12.1
        - Rust: 1.77.0
        - Node: 20.11.0
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Logs, screenshots, or anything else relevant
    validations:
      required: false
