name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature. Please describe what you'd like and why.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the project does this affect?
      options:
        - Python SDK
        - Rust SDK
        - TypeScript / WebMCP SDK
        - Specification
        - Schemas
        - Documentation
        - Tooling / CI
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it enable?
      placeholder: "I'm trying to... but currently..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other approaches you've considered and why they're insufficient
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Examples, references, mockups, or related issues
    validations:
      required: false
