name: VCP Enhancement Proposal (VEP)
description: Propose a change to the VCP specification
title: "VEP: "
labels: ["specification", "vep", "discussion"]
body:
  - type: markdown
    attributes:
      value: |
        VCP Enhancement Proposals (VEPs) follow a structured process. See [GOVERNANCE.md](https://github.com/Creed-Space/vcp-sdk/blob/main/GOVERNANCE.md#vcp-enhancement-proposals-veps) for the full lifecycle. A maintainer will assign a VEP number after triage.

  - type: dropdown
    id: layer
    attributes:
      label: Layer Affected
      description: Which layer of the VCP stack does this affect?
      options:
        - VCP/I -- Identity
        - VCP/T -- Transport
        - VCP/S -- Semantics
        - VCP/A -- Adaptation
        - Cross-cutting / multiple layers
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this change needed? What problem does it solve or what capability does it enable?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Change
      description: Describe the change in detail, including any new fields, formats, or behaviors
    validations:
      required: true

  - type: textarea
    id: compatibility
    attributes:
      label: Backward Compatibility Impact
      description: How does this affect existing implementations? What migration path is needed?
    validations:
      required: true

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change?
      description: Does this change break existing implementations?
      options:
        - "No"
        - "Yes"
    validations:
      required: true

  - type: textarea
    id: sdk_impact
    attributes:
      label: SDK Impact
      description: What changes would be needed in each SDK (Python, Rust, TypeScript)?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: References, prior art, related VEPs, or other relevant information
    validations:
      required: false
