"""Agent-intuitive facade for the VCP Agent Runtime Profile candidate."""

from .accretion import LocalAccretiveRuntime
from .cache import CacheKey, ContentAddressedCache
from .contracts import (
    AccretionCandidate,
    ActionIntent,
    Affordance,
    AffordanceQuery,
    AffordanceState,
    AgentResult,
    AssuranceAxis,
    AssuranceCheck,
    AssuranceOverall,
    AssuranceReport,
    AssuranceStatus,
    AuthorityGrantRef,
    CapabilityDescriptor,
    Contract,
    ControlCommand,
    ControlOperation,
    CursorDelta,
    DecisionKind,
    DecisionReceipt,
    EffectClass,
    EffectStatus,
    EventEnvelope,
    EvidenceClaim,
    ExecutionAttempt,
    ExecutionReceipt,
    ExpectedStateError,
    ExperienceCapsule,
    FailureFrame,
    Goal,
    InfluenceReceipt,
    NormativeClause,
    NormativeContext,
    ObjectionResponse,
    Omission,
    PlanStep,
    PredicateResult,
    Profile,
    ProfileAcknowledgement,
    ProfileOffer,
    PromotionRecord,
    ProofPlan,
    ProofPredicate,
    ResourceBudget,
    ResourceMeasurement,
    ResourceReport,
    ResultMeta,
    ResultStatus,
    RetryDisposition,
    RevocationRecord,
    RunProof,
    RunSpec,
    RunStatus,
    SafeTransition,
    SituationView,
)
from .controlled import LocalControlledRuntime
from .handles import RunHandle, SituationHandle
from .identity import RuntimeIdentity, runtime_identity
from .local import LocalReferenceRuntime, canonical_digest, default_descriptors
from .negotiation import negotiate_agent_runtime_profiles
from .runtime import AccretiveAgentRuntime, AgentRuntime, ControlledAgentRuntime
from .schema import (
    agent_runtime_schema,
    agent_runtime_schema_bytes,
    agent_runtime_schema_digest,
)
from .service import AccretiveService, ControlledService, ObserveService
from .transports import (
    DelegatingObserveTransport,
    HTTPObserveTransportStub,
    MCPObserveTransportStub,
)

__all__ = [
    "AccretionCandidate",
    "AccretiveAgentRuntime",
    "AccretiveService",
    "ActionIntent",
    "Affordance",
    "AffordanceQuery",
    "AffordanceState",
    "AgentResult",
    "AgentRuntime",
    "AssuranceAxis",
    "AssuranceCheck",
    "AssuranceOverall",
    "AssuranceReport",
    "AssuranceStatus",
    "AuthorityGrantRef",
    "CacheKey",
    "CapabilityDescriptor",
    "ContentAddressedCache",
    "Contract",
    "ControlCommand",
    "ControlOperation",
    "ControlledAgentRuntime",
    "ControlledService",
    "CursorDelta",
    "DecisionKind",
    "DecisionReceipt",
    "DelegatingObserveTransport",
    "EffectClass",
    "EffectStatus",
    "EventEnvelope",
    "EvidenceClaim",
    "ExecutionAttempt",
    "ExecutionReceipt",
    "ExpectedStateError",
    "ExperienceCapsule",
    "FailureFrame",
    "Goal",
    "HTTPObserveTransportStub",
    "InfluenceReceipt",
    "LocalAccretiveRuntime",
    "LocalControlledRuntime",
    "LocalReferenceRuntime",
    "MCPObserveTransportStub",
    "NormativeClause",
    "NormativeContext",
    "ObjectionResponse",
    "ObserveService",
    "Omission",
    "PlanStep",
    "PredicateResult",
    "Profile",
    "ProfileAcknowledgement",
    "ProfileOffer",
    "PromotionRecord",
    "ProofPlan",
    "ProofPredicate",
    "ResourceBudget",
    "ResourceMeasurement",
    "ResourceReport",
    "ResultMeta",
    "ResultStatus",
    "RetryDisposition",
    "RevocationRecord",
    "RunHandle",
    "RunProof",
    "RunSpec",
    "RunStatus",
    "RuntimeIdentity",
    "SafeTransition",
    "SituationHandle",
    "SituationView",
    "agent_runtime_schema",
    "agent_runtime_schema_bytes",
    "agent_runtime_schema_digest",
    "canonical_digest",
    "default_descriptors",
    "negotiate_agent_runtime_profiles",
    "runtime_identity",
]
