#!/usr/bin/env python3
"""Synchronize the canonical SDK publication-state record across VCP repos."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

SDK_ROOT = Path(__file__).resolve().parents[1]
SOURCE = SDK_ROOT / "release/publication-state.json"
STATUS_PAGE = SDK_ROOT / "release/ECOSYSTEM_STATUS.md"


def render_status(document: dict[str, object]) -> bytes:
    """Render the human-readable status page from the canonical JSON record."""
    protocol = document["protocol"]
    assert isinstance(protocol, dict)
    artifacts = document["artifacts"]
    assert isinstance(artifacts, list)
    conformance = document["conformance"]
    assert isinstance(conformance, dict)
    public_copy = document["public_copy_policy"]
    assert isinstance(public_copy, dict)
    rows = [
        ("Status", str(document["overall_state"]).replace("-", " ").title()),
        ("Source baseline", f"VCP {protocol['source_baseline']}"),
        (
            "Candidate protocol",
            f"VCP {protocol['candidate']}, {protocol['candidate_maturity']}",
        ),
        ("Conformance cases", str(conformance["case_count"])),
        ("Conformance fixtures", str(conformance["fixture_count"])),
        ("Protocol layers", str(conformance["protocol_layer_count"])),
        ("Extension suites", str(conformance["extension_suite_count"])),
        (
            "Implementation scope",
            (
                f"{conformance['full_project_controlled_implementations']} "
                "full project-controlled implementations, "
                f"{conformance['browser_integrations']} browser integration, "
                f"{conformance['independent_implementations']} independent implementations"
            ),
        ),
    ]
    for artifact in artifacts:
        assert isinstance(artifact, dict)
        rows.append(
            (
                str(artifact["id"]),
                f"{artifact['candidate_version']}, {artifact['state']}",
            )
        )
    rows.extend(
        [
            (
                "Registry commands",
                (
                    "Allowed"
                    if public_copy["registry_install_commands_allowed"]
                    else "Disallowed until publication receipts exist"
                ),
            ),
            ("Generated", str(document["as_of"])),
        ]
    )
    table = "\n".join(f"| {label} | {value} |" for label, value in rows)
    requirements = "\n".join(
        f"- {item}" for item in public_copy["publication_requirements"]
    )
    rendered = f"""# VCP Ecosystem Status

<!-- vcp-document-control
status: Generated source-only status
normative-authority: Publication-state record
protocol-version: VCP {protocol["source_baseline"]} source baseline
last-reviewed: {document["as_of"]} generated from canonical state
owner: VCP release maintainers
evidence-boundary: Generated status, not publication receipt
-->

> Generated byte-for-byte from
> `VCP-SDK/release/publication-state.json`. Edit that source record and run
> `scripts/sync_publication_state.py`; never edit this page directly.

| Field | Value |
|:---|:---|
{table}

## Claim boundary

{public_copy["required_label"]}

{conformance["claim_boundary"]}

This page establishes source-repository state only. It does not establish
registry publication, independent conformance, deployment identity, legal
approval, governance ratification, or production behavior.

## Publication requirements

{requirements}
"""
    return rendered.encode("utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--demo", required=True, type=Path)
    parser.add_argument("--spec", required=True, type=Path)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()

    body = SOURCE.read_bytes()
    document = json.loads(body)
    if document.get("schema") != "vcp-publication-state/1":
        parser.error("canonical publication state has an unsupported schema")

    json_targets = {
        args.demo.expanduser().resolve() / "static/status/publication-state.json",
        args.demo.expanduser().resolve() / "src/lib/data/publication-state.json",
        args.spec.expanduser().resolve() / "status/publication-state.json",
    }
    markdown = render_status(document)
    markdown_targets = {
        STATUS_PAGE,
        args.spec.expanduser().resolve() / "docs/ECOSYSTEM_STATUS.md",
    }
    failures = []
    for target in sorted(json_targets):
        if args.write:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(body)
        elif not target.is_file() or target.read_bytes() != body:
            failures.append(target)
    for target in sorted(markdown_targets):
        if args.write:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(markdown)
        elif not target.is_file() or target.read_bytes() != markdown:
            failures.append(target)

    if failures:
        for target in failures:
            print(f"publication-state drift: {target}")
        return 1

    digest = hashlib.sha256(body).hexdigest()
    verb = "synchronized" if args.write else "verified"
    print(f"publication state {verb}: sha256={digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
